banking_dbt:
  outputs:
    dev:
      account: am17332.ap-southeast-3.aws
      database: banking
      password: '@CitraNanda499'
      role: accountadmin
      schema: analytics
      threads: 4
      type: snowflake
      user: aditiaasas
      warehouse: COMPUTE_WH
  target: dev
